apiVersion: certmanager.k8s.io/v1alpha1

kind: ClusterIssuer

metadata:

  name: letsencrypt-production

  namespace: default

spec:

  acme:

    server: https://acme-v02.api.letsencrypt.org/directory

    email: danielraymartin@gmail.com

    privateKeySecretRef:

      name: letsencrypt-production

    dns01:

      providers:

      - name: clouddns

        clouddns:

          serviceAccountSecretRef:

            name: clouddns

            key: clouddns.key.json

          project: cje20-201714
