apiVersion: certmanager.k8s.io/v1alpha1

kind: ClusterIssuer

metadata:

  name: letsencrypt-staging

  namespace: default

spec:

  acme:

    server: https://acme-staging-v02.api.letsencrypt.org/directory

    email: dmartin@cloudbees.com

    privateKeySecretRef:

      name: letsencrypt-staging

    dns01:

      providers:

      - name: clouddns

        clouddns:

          serviceAccountSecretRef:

            name: clouddns

            key: clouddns.key.json

          project: ps-dev-201405
