kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: access-all-ps
subjects:
- kind: User	
  name: dmartin@cloudbees.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin-all 
  apiGroup: rbac.authorization.k8s.io
