apiVersion: certmanager.k8s.io/v1alpha1

kind: Certificate

metadata:

  name: core-devops-prod

  namespace: default

spec:

  secretName: core-devops

  issuerRef:

    name: letsencrypt-production

    kind: ClusterIssuer

  commonName: jenkins.core-devops.com

  dnsNames:

  - jenkins.core-devops.com

  acme:

    config:

    - dns01:

        provider: clouddns

      domains:

      - jenkins.core-devops.com
